---

- hosts: localhost
  gather_facts: false

  vars:
    btp_globalaccount_name: ""
    btp_subaccount_name: ""
    btp_subaccount_region: ""
    cloudfoundry_space_name: ""
    hana_cloud_admin_user: ""
    hanadb_instance_name: ""
    hanadb_schema_password: ""

  tasks:

    - ansible.builtin.import_role:
        name: sap_btp_hanacloud_cloudfoundry
        tasks_from: main.yml

...
